server:
  port: 8083

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3303/user-onseju
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.criteria.literal_handling_mode: BIND
      hibernate:
        connection.CharSet: UTF-8
        connection.characterEncoding: UTF-8
        connection.useUnicode: true
        format_sql: true

    database-platform: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /

jwt:
  secret:
    key: 7Iqk7YyM66W07YOA7L2U65Sp7YG065+9U3ByaW5n6rCV7J2Y7Yqc7YSw7LWc7JuQ67mI7J6F64uI64ukLg==

google:
  client:
    id: 112913425466-bmgoe7kca5d447g7p8i58oqka4g7r4fg.apps.googleusercontent.com
    secret: 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
  redirect:
    uri: http://localhost:3000/auth/callback
  token:
    uri: https://oauth2.googleapis.com/token
  userinfo:
    uri: https://www.googleapis.com/oauth2/v3/userinfo

chrome:
  extension:
    id: pijljcfdkaenmmlngfedhoffjfopfoef
