spring:
  application:
    name: user-service

  config:
    import: classpath:/env.properties

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.criteria.literal_handling_mode: BIND
      hibernate:
        connection.CharSet: UTF-8
        connection.characterEncoding: UTF-8
        connection.useUnicode: true
        format_sql: true

    database-platform: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    port: ${RABBITMQ_PORT}
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect:
    uri: ${GOOGLE_REDIRECT_URI}
  token:
    uri: ${GOOGLE_TOKEN_URI}
  userinfo:
    uri: ${GOOGLE_USER_INFO}

chrome:
  extension:
    id: ${CHROME_EXTENSION_ID}

